version: '3.7'

services:

  database:
    hostname: database
    restart: unless-stopped
    container_name: test_db
    image: mariadb:10.3.2
    env_file:
      - .env
      - ../.env
    environment:
      #- MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${DB_PASSWORD}    
